In [1]:
# Add the project root to the Python path
import sys
import os
sys.path.append(os.path.join(os.getcwd(), '..'))

from src.config.logging_config import setup_logging
from src.extract.weather_data import fetch_weather_data

# Reload modules when code is changed (uncomment for development)
%load_ext autoreload
%autoreload 2

In [2]:
logger = setup_logging(log_file="weather_data.log")

df = fetch_weather_data("2016-10-01", "2016-10-02")

2025-10-08 11:27:04,951 - src.extract.weather_data - INFO - Fetching weather data from 2016-10-01 to 2016-10-02
2025-10-08 11:27:04,958 - src.data_sources.weather - INFO - Fetching historical weather data from 2016-10-01 to 2016-10-02
2025-10-08 11:27:05,008 - src.data_sources.weather - INFO - Successfully processed 2 weather records
2025-10-08 11:27:05,010 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 2
2025-10-08 11:27:05,011 - src.extract.weather_data - INFO - Creating DataFrame from 2 records
2025-10-08 11:27:05,013 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 2

In [3]:
df.head()

,date,weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,sunrise,sunset,daylight_duration,sunshine_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,sunrise_time,sunset_time
0,2016-10-01 00:00:00+00:00,53.0,14.094833,18.8365,10.5865,1475300633,1475342431,41795.472656,36650.582031,1.2,1.2,0.0,3.0,18.391737,45.719997,2016-10-01 05:43:53,2016-10-01 17:20:31
1,2016-10-02 00:00:00+00:00,53.0,12.326084,14.8365,10.3365,1475387128,1475428700,41569.531250,34481.562500,1.3,1.3,0.0,4.0,25.582806,51.480000,2016-10-02 05:45:28,2016-10-02 17:18:20

In [5]:
# Change the timezone to Europe/Berlin in api call
df = fetch_weather_data("2016-10-01", "2016-10-02")
df.head()

2025-10-08 11:27:17,646 - src.extract.weather_data - INFO - Fetching weather data from 2016-10-01 to 2016-10-02
2025-10-08 11:27:17,647 - src.data_sources.weather - INFO - Fetching historical weather data from 2016-10-01 to 2016-10-02
2025-10-08 11:27:17,813 - src.data_sources.weather - INFO - Successfully processed 2 weather records
2025-10-08 11:27:17,814 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 2
2025-10-08 11:27:17,814 - src.extract.weather_data - INFO - Creating DataFrame from 2 records
2025-10-08 11:27:17,815 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 2

,date,weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,sunrise,sunset,daylight_duration,sunshine_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,sunrise_time,sunset_time
0,2016-09-30 22:00:00+00:00,53.0,14.284417,18.8365,10.5865,1475300633,1475342431,41814.261719,36650.582031,1.4,1.4,0.0,5.0,18.391737,45.719997,2016-10-01 05:43:53,2016-10-01 17:20:31
1,2016-10-01 22:00:00+00:00,53.0,12.321918,14.8365,10.3365,1475387128,1475428700,41588.398438,34481.562500,1.3,1.3,0.0,4.0,25.582806,51.480000,2016-10-02 05:45:28,2016-10-02 17:18:20

In [9]:
# Change date conversion in weather client
df = fetch_weather_data("2016-10-01", "2016-10-02")
df.head()

2025-10-08 11:31:27,294 - src.extract.weather_data - INFO - Fetching weather data from 2016-10-01 to 2016-10-02
2025-10-08 11:31:27,295 - src.data_sources.weather - INFO - Fetching historical weather data from 2016-10-01 to 2016-10-02
2025-10-08 11:31:27,304 - src.data_sources.weather - INFO - Successfully processed 2 weather records
2025-10-08 11:31:27,304 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 2
2025-10-08 11:31:27,305 - src.extract.weather_data - INFO - Creating DataFrame from 2 records
2025-10-08 11:31:27,307 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 2

,date,weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,sunrise,sunset,daylight_duration,sunshine_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,sunrise_time,sunset_time
0,2016-10-01 00:00:00+00:00,53.0,14.094833,18.8365,10.5865,1475300633,1475342431,41795.472656,36650.582031,1.2,1.2,0.0,3.0,18.391737,45.719997,2016-10-01 07:43:53+02:00,2016-10-01 19:20:31+02:00
1,2016-10-02 00:00:00+00:00,53.0,12.326084,14.8365,10.3365,1475387128,1475428700,41569.531250,34481.562500,1.3,1.3,0.0,4.0,25.582806,51.480000,2016-10-02 07:45:28+02:00,2016-10-02 19:18:20+02:00